stages:
  - test

test-rules:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^\[skip\] .*$/'
      when: never
  script:
    - echo "$CI_COMMIT_MESSAGE"

test-only:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\[skip\] .*$/
  script:
    - echo "$CI_COMMIT_MESSAGE"
