stages:
  - test

# Control job that always runs
test-control:
  stage: test
  script:
    - echo "$CI_COMMIT_MESSAGE"

# Don't run job if [skip] in commit message..
test-rules:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE !~ /^\[skip\]/'
  script:
    - echo "$CI_COMMIT_MESSAGE"
